version: '3.1'
services:

  ansible_meister:
    image: ubuntu
    container_name: ansible_meister
    restart: no
    networks:
      - 'ansible'
    ports:
      - 30022:22
    command: >
      bash -c "apt-get update         && apt-get install -y openssh-server         && mkdir -p /run/sshd && chmod 0755 /run/sshd         && service ssh start         && tail -f /dev/null"
  ansible_ziel1:
    image: ubuntu
    container_name: ansible_ziel1
    restart: no
    networks:
      - 'ansible'
    command: >
      bash -c "apt-get update         && apt-get install -y openssh-server         && mkdir -p /run/sshd && chmod 0755 /run/sshd         && service ssh start         && tail -f /dev/null"
  ansible_ziel2:
    image: ubuntu
    container_name: ansible_ziel2
    restart: no
    networks:
      - 'ansible'
    command: >
      bash -c "apt-get update         && apt-get install -y openssh-server         && mkdir -p /run/sshd && chmod 0755 /run/sshd         && service ssh start         && tail -f /dev/null"
  postgres:
    restart: unless-stopped
    image: postgres:14
    container_name: postgres
    networks:
        - 'ansible'
    volumes: 
      - semaphore-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: wtAoWYBP
      POSTGRES_DB: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 5000:3000
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    networks:
        - 'ansible'
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: wtAoWYBP
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: XgenaGLP
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: aCYHsfCmMgEenBHS
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes' 
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
    depends_on:
      - postgres
  
volumes:
  semaphore-postgres:
    driver: local

networks:
  ansible:
    driver: bridge

